# Generated by Django 3.2.8 on 2021-10-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitGroupApprovalTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.task')),
                ('groups_a', models.ManyToManyField(help_text='Pages at this step in a workflow will be moderated or approved by these groups of users', related_name='split_task_group_a', to='auth.Group', verbose_name='for Jan - June Daily Reflections')),
                ('groups_b', models.ManyToManyField(help_text='Pages at this step in a workflow will be moderated or approved by these groups of users', related_name='split_task_group_b', to='auth.Group', verbose_name='for Jul - Dec Daily Reflections')),
            ],
            options={
                'verbose_name': 'reflection-month-dependent approval task',
                'verbose_name_plural': 'reflection-month-dependent approval tasks',
            },
            bases=('wagtailcore.task',),
        ),
    ]
